// Edit this file to change the wording shown in the app.
export const content = {
  site: {
    title: 'Våra minnen',
    description: 'En privat tidskapsel för våra gemensamma minnen.',
  },
  app: {
    opening: 'Öppnar våra minnen…',
    sessionExpired: 'Din session har gått ut. Logga in igen.',
    footer: 'Jag älskar dig',
  },
  login: {
    heading: 'Logga in för att öppna',
    username: 'Användarnamn',
    password: 'Lösenord',
    open: 'Öppna',
    opening: 'Öppnar…',
    invalidCredentials: 'Användarnamnet eller lösenordet är fel.',
  },
  timeline: {
    heading: 'Våra minnen',
    add: '+ Lägg till ett minne',
    retry: 'Försök igen',
    loading: 'Hämtar våra minnen…',
    savedOne: 'sparat minne',
    savedMany: 'sparade minnen',
    newestFirst: 'Nyaste först',
    emptyHeading: 'Lägg till ett minne',
    addFirst: 'Lägg till vårt första minne',
    pages: 'Minnessidor',
    newer: 'Nyare minnen',
    older: 'Äldre minnen',
    page: (current: number, total: number) => `Sida ${current} av ${total}`,
    deleted: 'Minnet har tagits bort.',
    saved: 'Minnet har sparats.',
  },
  memory: {
    readMore: 'Läs mer',
    readLess: 'Visa mindre',
    edit: 'Redigera minnet',
    delete: 'Ta bort',
    deleting: 'Tar bort…',
    confirmDelete: 'Ja, ta bort minnet',
    keep: 'Behåll minnet',
    deleteQuestion: (title: string) =>
      `Vill du ta bort ”${title}” och alla dess bilder för alltid?`,
    editLabel: (title: string) => `Redigera ${title}`,
    deleteLabel: (title: string) => `Ta bort ${title}`,
  },
  editor: {
    editHeading: 'Några fler detaljer…',
    newHeading: 'Minns du när…',
    introduction: 'Skriv ner det precis som du minns det.',
    reload: 'Hämta sparad version',
    title: 'Ge minnet en rubrik',
    date: 'När var det?',
    location: 'Var?',
    optional: '(valfritt)',
    story: 'Berätta om minnet',
    images: 'Bilder',
    imageHelp: 'JPEG eller PNG. Högst 10 MB per bild och 10 bilder per minne.',
    pendingImages: 'Bilder att spara',
    save: 'Spara minnet',
    saving: 'Sparar…',
    cancel: 'Avbryt',
    remove: 'Ta bort',
    unsupportedImages: 'Välj bilder i JPEG- eller PNG-format.',
    imageTooLarge: 'Varje bild får vara högst 10 MB.',
    tooManyImages: 'Välj högst 10 bilder åt gången.',
    uploadFailed: 'Minnet har sparats, men en bild kunde inte laddas upp. ',
    replaceDraft: 'Vill du ersätta ditt utkast med den senast sparade versionen?',
    discardDraft: 'Vill du slänga dina osparade ändringar?',
    previewLabel: (name: string) => `Förhandsvisning av ${name}`,
    removeLabel: (name: string) => `Ta bort ${name}`,
  },
  gallery: {
    loadFailed: 'Bilderna kunde inte visas.',
    retry: 'Försök igen',
    previous: 'Föregående bild',
    next: 'Nästa bild',
    imagesLabel: 'Bilder till minnet',
    remove: 'Ta bort bild',
    removing: 'Tar bort…',
    confirmRemove: 'Vill du ta bort bilden för alltid?',
    position: (current: number, total: number) => `Bild ${current} av ${total}`,
    openLabel: (number: number, title: string) => `Öppna bild ${number} till ${title}`,
    removeLabel: (number: number) => `Ta bort bild ${number}`,
  },
  errors: {
    network: 'Det gick inte att nå servern. Kontrollera din anslutning och försök igen.',
    tooManyAttempts: 'För många inloggningsförsök. Vänta en stund och försök igen.',
    invalidInput: 'Kontrollera uppgifterna och försök igen.',
    sessionExpired: 'Din session har gått ut. Logga in igen.',
    verification: 'Det gick inte att verifiera din begäran. Försök igen.',
    missingMemory: 'Det här minnet finns inte längre.',
    imageTooLarge: 'Bilden är för stor. Välj en bild på högst 10 MB och 20 megapixlar.',
    invalidImage: 'Välj en giltig JPEG- eller PNG-bild.',
    imageLimit: 'Ett minne kan ha högst 10 bilder. Ta bort en bild innan du lägger till fler.',
    conflict:
      'Minnet har ändrats på annat håll. Ditt utkast finns kvar här. Hämta den sparade versionen innan du fortsätter redigera.',
    generic: 'Något gick fel. Försök igen.',
  },
} as const
